events {}

http {
  server {
    listen 80;

    location / {
      return 200 "ok\n";
    }
  }

  server {
    listen 8080;

    location /stub_status {
      stub_status;
      allow all;
    }
  }
}
